"""Regenerates Figure 3 (Example use of GeoMERIT) from the released model."""
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import patches
from geophysical_method_selector_v2 import GeophysicalMethodSelectorV2
sel=GeophysicalMethodSelectorV2()
nice=lambda m:m.replace("Induced_Polarization","Induced Polarization").replace("Seismic_Refraction","Seismic Refraction").replace("Self_Potential","Self-Potential")
p=dict(target='groundwater',target_depth=50,conductivity=100,noise_level=20,budget=5000,time_constraint=3,required_resolution=0.7)
rk=sel.rank_methods(p)
print("Top recommendation:", rk[0][0], round(rk[0][1],1))
for i,(m,s) in enumerate(rk,1): print(f"{i:>2} {nice(m):<22} {s:6.1f}")
print("(Figure 3 image is generated by the plotting block in the manuscript build; values above are the figure content.)")
